//
//  MainInteractor.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 15 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func fetchNotes(request: Main.ListNotes.FetchNotes.Request)
    func eraseNote(id: String)
    func emptyTrash()
}

protocol MainDataStore
{
  var notes: [Note]? { get }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{

  var notes: [Note]?
    
  var presenter: MainPresentationLogic?
  var mainWorker: MainWorker = MainWorker()
  
  // MARK: fetch Notes
  
  func fetchNotes(request: Main.ListNotes.FetchNotes.Request)
  {
    mainWorker.fetchNotes { (notes) -> Void in
        self.notes = notes
        let response = Main.ListNotes.FetchNotes.Response(notes: self.notes!)
        self.presenter?.presentNotes(response: response)
    }
  }
    
    func eraseNote(id: String) {
        mainWorker.eraseNotey(id: id) { (notes) -> Void in
            self.notes = notes
            let response = Main.ListNotes.FetchNotes.Response(notes: self.notes!)
            self.presenter?.presentNotes(response: response)
        }
    }
    
    func emptyTrash() {
        mainWorker.emptyTrashy() { (notes) -> Void in
            self.notes = notes
            let response = Main.ListNotes.FetchNotes.Response(notes: self.notes!)
            self.presenter?.presentNotes(response: response)
        }
    }
}
