//
//  MainRouter.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 15 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic
{
    func routeToCreateNote(segue: UIStoryboardSegue?)
    func routeToEditNote(segue: UIStoryboardSegue?)
}

protocol MainDataPassing
{
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing
{
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    // MARK: Routing
    
    func routeToCreateNote(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditNoteViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateNote(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "EditNoteViewController") as! EditNoteViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateNote(source: dataStore!, destination: &destinationDS)
            navigateToCreateNote(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToEditNote(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! EditNoteViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditNote(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "EditNoteViewController") as! EditNoteViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditNote(source: dataStore!, destination: &destinationDS)
            navigateToEditNote(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToCreateNote(source: MainViewController, destination: EditNoteViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToEditNote(source: MainViewController, destination: EditNoteViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToCreateNote(source: MainDataStore, destination: inout EditNoteDataStore)
    {
    }
    
    func passDataToEditNote(source: MainDataStore, destination: inout EditNoteDataStore)
    {
        let selectedRow = viewController?.listOfNotes?.indexPathForSelectedRow?.row
        if (selectedRow != nil) {
            destination.note = (source.notes?[selectedRow!])!
        }
    }
}

