//
//  MainPresenter.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 15 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentNotes(response: Main.ListNotes.FetchNotes.Response)
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  
  // MARK: Do something
  
  func presentNotes(response: Main.ListNotes.FetchNotes.Response)
  {
    var editableNotes = [Main.ListNotes.FetchNotes.ViewModel.DisplayedNote]()
    var trashNotes = [Main.ListNotes.FetchNotes.ViewModel.DisplayedNote]()
    for note in response.notes {
        if (note.trash) {
            trashNotes.append(Main.ListNotes.FetchNotes.ViewModel.DisplayedNote(title:note.title,content:note.text))
        }
        else {
          editableNotes.append(Main.ListNotes.FetchNotes.ViewModel.DisplayedNote(title:note.title,content:note.text))
        }
    }
    let viewModel = Main.ListNotes.FetchNotes.ViewModel(editableNotes: editableNotes, trashNotes: trashNotes)
    viewController?.displayFetchedNotes(viewModel: viewModel)
  }
}
