//
//  EditNoteRouter.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 16 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditNoteRoutingLogic
{
  func routeToListOrders(segue: UIStoryboardSegue?)
}

protocol EditNoteDataPassing
{
  var dataStore: EditNoteDataStore? { get }
}

class EditNoteRouter: NSObject, EditNoteRoutingLogic, EditNoteDataPassing
{
  weak var viewController: EditNoteViewController?
  var dataStore: EditNoteDataStore?
  
  // MARK: Routing
  
    
    
    func routeToListOrders(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! MainViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToListNotes(source: dataStore!, destination: &destinationDS)
        } else {
            let index = viewController!.navigationController!.viewControllers.count - 2
            let destinationVC = viewController?.navigationController?.viewControllers[index] as! MainViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToListNotes(source: dataStore!, destination: &destinationDS)
            navigateToListNotes(source: viewController!, destination: destinationVC)
        }
    }
    
  // MARK: Navigation
  
    func navigateToListNotes(source: EditNoteViewController, destination: MainViewController)
    {
        source.navigationController?.popViewController(animated: true)
    }
    
  
  // MARK: Passing data
  
    func passDataToListNotes(source: EditNoteDataStore, destination: inout MainDataStore)
    {
        
    }
}
