//
//  EditNotePresenter.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 16 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNotePresentationLogic
{
  func presentSomething(response: EditNote.Something.Response)
}

class EditNotePresenter: EditNotePresentationLogic
{
  weak var viewController: EditNoteDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EditNote.Something.Response)
  {
    let viewModel = EditNote.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
