//
//  EditNotePresenter.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 16 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNotePresentationLogic
{
  func presentNoteToEdit(response: EditNote.ShowNote.Response)
    func presentCreatedNote(response: EditNote.CreateNote.Response)
}

class EditNotePresenter: EditNotePresentationLogic
{
  weak var viewController: EditNoteDisplayLogic?
  
    // MARK: - Create note
    
    func presentCreatedNote(response: EditNote.CreateNote.Response)
    {
        let viewModel = EditNote.ShowNote.ViewModel(note: response.note)
        viewController?.displayNote(viewModel: viewModel)
    }
    
    func presentNoteToEdit(response: EditNote.ShowNote.Response) {
        let viewModel = EditNote.ShowNote.ViewModel(note: response.note)
        viewController?.displayNote(viewModel: viewModel)
    }
}
