//
//  EditNoteWorker.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 16 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EditNoteWorker
{
    var notesWorker = NotesWorker(notesStore: NotesSimpleStore())
    
    func createNote(completionHandler: @escaping (Note?) -> Void) {
        notesWorker.createNote() { note in
            completionHandler(note)
        }
    }
    
    func saveNote(noteToSave: Note, completionHandler: @escaping (Note?) -> Void) {
        notesWorker.saveNote(noteToSave: noteToSave) { note in
            completionHandler(note)
        }
    }
    
    func eraseNote(id: String, completionHandler: @escaping (Note?) -> Void) {
        notesWorker.eraseNote(id: id) { note in
            completionHandler(note)
        }
    }
}
