//
//  EditNoteInteractor.swift
//  CleanSwiftNotes
//
//  Created by Andy Weinstein on 16 Tevet 5780.
//  Copyright (c) 5780 AW. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNoteBusinessLogic
{
  func doSomething(request: EditNote.Something.Request)
}

protocol EditNoteDataStore
{
  //var name: String { get set }
}

class EditNoteInteractor: EditNoteBusinessLogic, EditNoteDataStore
{
  var presenter: EditNotePresentationLogic?
  var worker: EditNoteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditNote.Something.Request)
  {
    worker = EditNoteWorker()
    worker?.doSomeWork()
    
    let response = EditNote.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
